/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gg;

/**
 *
 * @author PNC2
 */
public class store extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public store() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side = new javax.swing.JPanel();
        icon2 = new javax.swing.JLabel();
        icon4 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        box1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side.setBackground(new java.awt.Color(153, 255, 153));
        side.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mouseicon.PNG"))); // NOI18N
        side.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 80, 60));

        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keyboardicon.PNG"))); // NOI18N
        side.add(icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 80, 60));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headseticon.PNG"))); // NOI18N
        side.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 90, 60));

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/accessories.PNG"))); // NOI18N
        side.add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 80, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/side (1).png"))); // NOI18N
        jLabel11.setText("jLabel11");
        side.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 530));

        getContentPane().add(side, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 530));

        jLabel1.setBackground(new java.awt.Color(102, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1 (1).png"))); // NOI18N
        jLabel1.setText("sdf");

        jLabel2.setBackground(new java.awt.Color(102, 255, 204));
        jLabel2.setText("rf");

        jLabel3.setBackground(new java.awt.Color(102, 255, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2 (1).png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(102, 255, 204));
        jLabel4.setText("yh");

        jLabel5.setBackground(new java.awt.Color(102, 255, 204));
        jLabel5.setText("gh");

        javax.swing.GroupLayout box1Layout = new javax.swing.GroupLayout(box1);
        box1.setLayout(box1Layout);
        box1Layout.setHorizontalGroup(
            box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        box1Layout.setVerticalGroup(
            box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        main.setBackground(new java.awt.Color(204, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2 ().png"))); // NOI18N
        main.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 530, 360));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg (2).jpg"))); // NOI18N
        main.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 530));

        jLabel8.setText("jLabel6");
        main.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 670, 360));

        jLabel9.setText("jLabel6");
        main.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 670, 360));

        jLabel10.setText("jLabel6");
        main.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 670, 360));

        jLabel7.setText("jLabel7");
        main.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new store().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPanel box1;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel main;
    private javax.swing.JPanel side;
    // End of variables declaration//GEN-END:variables
}
